# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ZYNQ) += \
	zynq-cc108.dtb \
	zynq-ebaz4205.dtb \
	zynq-microzed.dtb \
	zynq-parallella.dtb \
	zynq-zc702.dtb \
	zynq-zc706.dtb \
	zynq-zc770-xm010.dtb \
	zynq-zc770-xm011.dtb \
	zynq-zc770-xm012.dtb \
	zynq-zc770-xm013.dtb \
	zynq-zed.dtb \
	zynq-zturn.dtb \
	zynq-zturn-v5.dtb \
	zynq-zybo.dtb \
	zynq-zybo-z7.dtb \
	zynq-zc702-ad9361-fmcomms2-3.dtb \
	zynq-zc702-ad9361-fmcomms5.dtb \
	zynq-zc706-ad9361-fmcomms2-3.dtb \
	zynq-zc706-ad9361-fmcomms5.dtb \
	zynq-zed-ad9361-fmcomms2-3.dtb
