# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_GENESYS2_VERONICA) += afrl_genesys2_veronica.dtb
dtb-$(CONFIG_ARCH_NEXYS_VERONICA) += afrl_nexys_veronica.dtb
dtb-$(CONFIG_ARCH_KC705_VERONICA) += afrl_KC705_veronica.dtb
dtb-$(CONFIG_ARCH_NETFPGA-1G-CML_VERONICA) += afrl_netfpga-1G-cml_veronica.dtb
dtb-$(CONFIG_ARCH_VC707_VERONICA) += afrl_vc707_veronica.dtb
